USE QuanLyWebBookingHotel
GO

INSERT INTO Countries (ISO_Code, Country_Name) VALUES
('VN', 'Vietnam'),
('US', 'United States'),
('JP', 'Japan'),
('FR', 'France'),
('DE', 'Germany'),
('CN', 'China'),
('IN', 'India'),
('BR', 'Brazil'),
('RU', 'Russia'),
('GB', 'United Kingdom'),
('CA', 'Canada'),
('AU', 'Australia'),
('IT', 'Italy'),
('ES', 'Spain'),
('MX', 'Mexico'),
('KR', 'South Korea'),
('ID', 'Indonesia'),
('NL', 'Netherlands'),
('SA', 'Saudi Arabia'),
('TR', 'Turkey'),
('ZA', 'South Africa'),
('SE', 'Sweden'),
('NO', 'Norway'),
('FI', 'Finland'),
('DK', 'Denmark'),
('IE', 'Ireland'),
('PT', 'Portugal'),
('BE', 'Belgium'),
('AT', 'Austria'),
('CH', 'Switzerland'),
('PL', 'Poland'),
('CZ', 'Czech Republic'),
('HU', 'Hungary'),
('GR', 'Greece'),
('RO', 'Romania'),
('SK', 'Slovakia'),
('BG', 'Bulgaria'),
('SI', 'Slovenia'),
('HR', 'Croatia'),
('EE', 'Estonia'),
('LV', 'Latvia'),
('LT', 'Lithuania'),
('IS', 'Iceland'),
('MT', 'Malta'),
('CY', 'Cyprus'),
('LU', 'Luxembourg'),
('AD', 'Andorra'),
('MC', 'Monaco'),
('SM', 'San Marino'),
('VA', 'Vatican City'),
('MK', 'North Macedonia'),
('RS', 'Serbia'),
('AL', 'Albania'),
('BA', 'Bosnia and Herzegovina'),
('ME', 'Montenegro'),
('KZ', 'Kazakhstan'),
('UA', 'Ukraine'),
('BY', 'Belarus'),
('MD', 'Moldova'),
('AM', 'Armenia'),
('GE', 'Georgia'),
('AZ', 'Azerbaijan'),
('TJ', 'Tajikistan'),
('KG', 'Kyrgyzstan'),
('UZ', 'Uzbekistan'),
('TM', 'Turkmenistan'),
('SG', 'Singapore'),
('MY', 'Malaysia'),
('PH', 'Philippines'),
('TH', 'Thailand'),
('BD', 'Bangladesh'),
('LK', 'Sri Lanka'),
('NP', 'Nepal'),
('MV', 'Maldives'),
('MM', 'Myanmar'),
('KH', 'Cambodia'),
('LA', 'Laos'),
('MN', 'Mongolia'),
('BT', 'Bhutan'),
('TL', 'Timor-Leste'),
('FJ', 'Fiji'),
('PG', 'Papua New Guinea'),
('SB', 'Solomon Islands'),
('VU', 'Vanuatu'),
('WS', 'Samoa'),
('TV', 'Tuvalu'),
('KI', 'Kiribati'),
('MH', 'Marshall Islands'),
('FM', 'Micronesia'),
('AS', 'American Samoa'),
('GU', 'Guam'),
('PR', 'Puerto Rico'),
('HT', 'Haiti'),
('DO', 'Dominican Republic'),
('JM', 'Jamaica'),
('TT', 'Trinidad and Tobago'),
('BB', 'Barbados'),
('BS', 'Bahamas'),
('KY', 'Cayman Islands'),
('BM', 'Bermuda');
GO